### ISSUE TITLE
Enable everything ?

### ISSUE THREAD

**Issue by MatMaul** [flathub/org.freedesktop.Platform.ffmpeg#1] opened 2018-01-18 10:03 UTC
Is there any reason to not enable all formats here ?

For the VLC use case at least AAC encoding and HEVC decoding would be pretty useful.
Decoding of DTS, AC3 and their various HD extensions too.

**Comment by TingPing** [comment] 2018-01-18 10:49
There is a security cost to codecs but AAC, HEVC, AC3, etc are popular enough to make sense.

**Comment by TingPing** [comment] 2018-01-18 10:50
Also re *encoding*, it was decided that the versions in the runtime should be focused on decoding. Applications that support encoding are probably complex enough to want their own `ffmpeg`.

**Comment by nedrichards** [comment] 2018-01-18 12:51
VLC really want a fully enabled ffmpeg, that's their users expectations - and that's certainly not suitable for most other applications.

**Comment by TingPing** [comment] 2018-01-18 13:00
Media decoding is probably the second biggest attack surface for untrusted input beyond web browsers. As security is one of the biggest goals of Flatpak I don't think codec support should be taken lightly just to claim that an obscure codec is supported out of the box.

VLC supporting re-encoding it makes sense for it to bundle its own ffmpeg and if the maintainer of that wants to take responsibility for it then fine but the runtime version I think should limit its exposure.

**Comment by TingPing** [comment] 2018-01-18 13:06
It is also worth noting this extension point does largely exist for one purpose: Companies who must respect patents to ship projects that depend upon ffmpeg. The one in the runtime probably won't be used by many projects on flathub unless their usage is entirely covered by the free-codec version.

**Comment by MatMaul** [comment] 2018-01-18 13:34
Fine for me.

**Comment by TingPing** [comment] 2018-01-18 13:48
Anyway like I said some do make sense so feel free to open a PR for HEVC, etc.

**Comment by MatMaul** [comment] 2018-01-19 08:01
I just noticed that this could be used by packaged Firefox so I agree that heavily used codecs should be included. I'll send a PR.
@alexlarsson I think you can include basic AC3 in the freedesktop version, last patent (at least for decoding) as expired last year. Also adding `--enable-hwaccel=vp9_vaapi` could be useful to some (vpx_vdpau and vp8_vaapi don't exist).

**Comment by TingPing** [comment] 2018-01-19 08:17
Firefox is the reason this exists =)

**Comment by MatMaul** [comment] 2018-01-19 18:28
Added, but HEVC is not currently supported in Firefox. I guess it makes sense since without HW decoding 4K HEVC is a "bit" hard on the CPU.

**Comment by ramcq** [comment] 2018-03-07 03:07
Hmm... not hugely keen on this. Endless licenses the mandatory HTML5 codecs - ie AAC, H.264 - when we ship a machine. We don't license HEVC because it's lightly used and obnoxiously expensive. The original purpose of this extension was that Mozilla would be able to load the mandatory HTML5 codecs via Flatpak if the user was able to install / vendor able to ship this extension. On the fully-licensed OS images we ship, we could ship the old .ffmpeg extension, but we can't ship this one, so this is a bit of a regression for us - we shouldn't ever ship HEVC.

**Comment by ramcq** [comment] 2018-03-07 03:08
If we supported branches I guess we could publish some branches, /html5 and /full or something? Add it to the list... :/

**Comment by TingPing** [comment] 2018-03-07 03:38
I don't think branches will save you. They are used to match the runtime and  the extensions are all auto loaded so who gets priority?

**Comment by MatMaul** [comment] 2018-03-07 06:19
Understandable. I am fine reverting, considering the target is basically only Firefox and HEVC is not even working now.

What about VLC for example? You don't ship it by default so you are fine ?

**Comment by ramcq** [comment] 2018-03-07 06:26
Yeah, we have a blacklist to keep certain things out of our images, so VLC just never gets pre-installed. For instance I've split Pitivi to provide its HEVC decoders/encoders, AAC and H264, etc in a separate extension which I can blacklist in the image builder. Is HEVC expected to be used for HTML5 content?

**Comment by ramcq** [comment] 2018-03-07 06:33
I don't feel _massively_ strongly because what will happen is that people will auto-download the ffmpeg extension on an app install/runtime update anyway. Maybe we could add versions=1.6;default; to the runtime .json and provide the OS libavcodec as an unmanaged extension?

**Comment by MatMaul** [comment] 2018-03-07 07:59
I don't know for HEVC HTML5 support, it is not clear, I think the codec is not specified in the spec so it all comes down to vendor implementation.
I am fine removing it, especially considering the licenses are outrageous and they didn't even manage to have a unique patents pool.....

What is this unmanaged extension thing ?

**Comment by MatMaul** [comment] 2018-03-07 08:03
And for the audio codecs ?
I guess AAC is safe since a H264 license without the AAC one is not that useful :)
AC3 has no more valid patents, so what's left is DTS/AC3 extensions and TrueHD.
Perhaps we should removed them, it is not used on the web and I think Dolby and DTS are a bit picky about having licenses...

**Comment by nedrichards** [comment] 2018-03-08 14:18
It's webrtc which required h264 - and that uses opus or g711 by default - so yes, in that case no aac is useful ;-) (not directly on point but potentially helpful context)

**Comment by TingPing** [comment] 2018-03-08 19:07
According to Red Hat legal aac is distributable by them now anyway

**Comment by ramcq** [comment] 2018-03-08 19:43
No: only one specific AAC implementation is. They have a branch of fdk-aac with some code deleted. I have a vague plan to go and put that into the runtime and make gst/ffmpeg/etc use it. But, not got around to it yet. (The AAC patent licensing folks themselves have acknowledged that if you're not using any of the high-end profiles, no royalty is due.)

**Comment by TingPing** [comment] 2018-03-08 19:48
That was only for the encoder, `ffmpeg`'s decoding support may have different patents apply or not.

**Comment by ramcq** [comment] 2018-03-08 19:51
You can link ffmpeg to fdk-aac so you get the "blessed" AAC.

**Comment by Nine-H** [comment] 2020-09-16 05:41
does anyone know of an ffmpeg flatpak I can depend on without having to be the vendor myself? the lack of filters and encoding makes this version useless.

edit: cheers tim.

**Comment by tim77** [comment] 2020-09-16 05:45
@Nine-H latest freedesktop runtime 20.08 `.ffmpeg-full` extension improved a lot so try it. See example https://github.com/flathub/org.atheme.audacious/blob/master/org.atheme.audacious.yaml#L5

**Comment by TingPing** [comment] 2020-09-16 21:03
I'll just close this as this repo isn't relevant any more.

**Closed by TingPing** 2020-09-16 21:03 UTC
